### PR TITLE
fix + docs: fix #568, #555 & update docs

### LINKED ISSUE #568: 提问一下关于文档的 LAUNCH_APP_FROM_H5 这部分
作者你好，我使用这个库比较久了，之前使用都是正常的，不知道从什么时候开始ios上出问题了：能正常跳转到应用，universallink检查了是对的，但是跳转携带的参数都变成null了。
分享到微信、拉起微信客服、微信支付这些功能都是可用的，只有微信开放标签跳转过来参数获取不到。

我想请问一下这个现象是我没有在 AppDelegate中主动注册WXApi导致的吗。

另外，我想请问作者能不能帮忙提供一下你的示例代码的 swift 版本 (就是[这里](https://github.com/OpenFlutter/fluwx/blob/5ef94a3837e5d7433c7e3835e88acacff8ee3afa/doc/LAUNCH_APP_FROM_H5_CN.md) 的oc代码)。oc 和 swift 我都不会写，看着oc我写不出 swift /(ㄒoㄒ)/~~

感谢作者

### PR DESCRIPTION
**Pull request by lopo12123**
- update doc for section [Launch App From H5](https://github.com/OpenFlutter/fluwx/blob/master/doc/LAUNCH_APP_FROM_H5.md)
- cache open url request when WXApi is not registered, and handle it once WXApi is registered (fix [#555](https://github.com/OpenFlutter/fluwx/issues/555) and [#568](https://github.com/OpenFlutter/fluwx/issues/568))

---

主要解决了 iOS 端的冷启动参数传递问题，不再需要在原生代码的 `AppDelegate` 中初始化 `WXApi`，对冷启动参数的处理双端保持一致

经过简单测试，`addSubscriber` 和 `getExtMsg` 都正常可用

### CODE REVIEW

**Comment by JarvanMo** [comment]
You rock man! You do awesome work that I'm not familiar with.

File: ios/Classes/FluwxPlugin.m [hunk 1]
```diff
@@ -370,27 +394,55 @@ - (void)handelGetExtMsgWithCall:(FlutterMethodCall *)call result:(FlutterResult)
...
+        // unregistered -- cache open url request and handle it once WXApi is registered
+        __weak typeof(self) weakSelf = self;
+        _cachedOpenUrlRequest = ^() {
+          __strong typeof(weakSelf) strongSelf = weakSelf;
+          [WXApi handleOpenURL:url delegate:strongSelf];
+        };
+
+
+        // simply return YES to indicate that we can handle open url request later
+        return YES;
```
Comment (JarvanMo) [inline ios/Classes/FluwxPlugin.m:432]: Can we `return NO;` because it consumes callbacks handling, such as AliPay.
